(define (problem boxman5)
    (:domain boxman_domain)
    (:objects  X1 X2 X3 X4 X5 X6 - loc)
    (:init 
    (inc X1 X2)
    (inc X2 X3)
    (inc X3 X4)
    (inc X4 X5)
    (inc X5 X6)
    (box X3 X3)
    (box X4 X2)
    (box X5 X4)
    (empty X1 X1)
    (empty X1 X2)
    (empty X2 X1)
    (empty X2 X2)
    (empty X3 X1)
    (empty X3 X2)
    (empty X3 X4)
    (empty X3 X5)
    (empty X3 X6)
    (empty X4 X3)
    (empty X4 X4)
    (empty X4 X5)
    (empty X4 X6)
    (empty X5 X2)
    (empty X6 X1)
    (empty X6 X2)
    (person X6 X4)
    )
    (:goal 
    (and
    (box X3 X2)
    (box X3 X3)
    (box X6 X2)
    
    )
    )

)

